#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# Project: ershouche

from pyspider.database.mysql.mysqldb import ToMysql
import pandas as pd
from pypinyin import lazy_pinyin
import sys

# con = pymysql.connect(host='localhost', user='root', passwd='luoxue99', db='ershouche', charset='utf8')
# c2_youxin2 = pd.read_sql('select * from ershouche_youxin', con=con)
# con.close()
# col_name = c2_youxin2.columns
# print(col_name)



kwargs = {  'host':'localhost',
            'user':'root',
            'passwd':'luoxue99',
            'db':'ershouche',
            'charset':'utf8'}
sql = ToMysql(kwargs)

list_var = ['paiqiliang', 'baigonglijiasu', 'zhengbeizhiliang', 'zhouju', 'fadongjixinghao', 'biansuxiang', 'pailiang',
       'ranliaoleixing', 'qudongxingshi', 'zongheyouhao', 'jibenxinxi1',
        'fadongjicanshu', 'dipancanshu',
        'xingnengcanshu', 'gengduocanshu'
       ]

for list_var_i in list_var:
    sql_query = "select distinct " + list_var_i + " from ershouche_youxin"
    rows = sql.select(sql_query)
    print(list_var_i, "\n", "------")
    for row in rows:
        print(row)


